// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoGa9Iirc7jbm_P0TUWGrowDW9zLPGUHA',
    appId: '1:875491121216:web:cfcf37f396afb2995067a5',
    messagingSenderId: '875491121216',
    projectId: 'tennis-weather-app',
    authDomain: 'tennis-weather-app.firebaseapp.com',
    storageBucket: 'tennis-weather-app.appspot.com',
    measurementId: 'G-3T6Q2R21PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApi6VLTzOXbUgmte8SWFieWQA3t2rIjuc',
    appId: '1:875491121216:android:abf5f99048e7a7f25067a5',
    messagingSenderId: '875491121216',
    projectId: 'tennis-weather-app',
    storageBucket: 'tennis-weather-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5pJwfUGBOWGsTnmIbfH94o6L3KLXSUtg',
    appId: '1:875491121216:ios:4ee3d2a0a35a40c85067a5',
    messagingSenderId: '875491121216',
    projectId: 'tennis-weather-app',
    storageBucket: 'tennis-weather-app.appspot.com',
    iosBundleId: 'com.example.helpingATennisPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5pJwfUGBOWGsTnmIbfH94o6L3KLXSUtg',
    appId: '1:875491121216:ios:4ee3d2a0a35a40c85067a5',
    messagingSenderId: '875491121216',
    projectId: 'tennis-weather-app',
    storageBucket: 'tennis-weather-app.appspot.com',
    iosBundleId: 'com.example.helpingATennisPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoGa9Iirc7jbm_P0TUWGrowDW9zLPGUHA',
    appId: '1:875491121216:web:38dbb3b20f5b38565067a5',
    messagingSenderId: '875491121216',
    projectId: 'tennis-weather-app',
    authDomain: 'tennis-weather-app.firebaseapp.com',
    storageBucket: 'tennis-weather-app.appspot.com',
    measurementId: 'G-YNV346PK68',
  );
}
